# Generated by Django 6.0.5 on 2026-09-10 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appelli', '0009_gruppo_presidente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studenteappellodilaurea',
            name='tutor',
            field=models.ForeignKey(blank=True, help_text='Docente che segue lo studente per questa tesi.', limit_choices_to={'groups__name': 'docente'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tutorati', to=settings.AUTH_USER_MODEL, verbose_name='Tutor'),
        ),
    ]
