# Generated by Django 6.0.5 on 2026-09-11 08:43

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appelli', '0010_tutor_iscrizione'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studenteappellodilaurea',
            name='giudizio',
            field=models.TextField(blank=True, help_text='Giudizio del tutor. Non visibile allo studente.', verbose_name='Giudizio'),
        ),
        migrations.AddField(
            model_name='studenteappellodilaurea',
            name='punteggio',
            field=models.SmallIntegerField(blank=True, help_text='Punti che il tutor propone di aggiungere al voto di laurea (da 0 a 2). Vuoto = non ancora valutato.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Punti proposti'),
        ),
        migrations.AddConstraint(
            model_name='studenteappellodilaurea',
            constraint=models.CheckConstraint(condition=models.Q(('punteggio__isnull', True), models.Q(('punteggio__gte', 0), ('punteggio__lte', 2)), _connector='OR'), name='punteggio_nell_intervallo_ammesso'),
        ),
    ]
